import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  isAuthenticated,
  children,
}: Readonly<{
  children: React.ReactNode;
  isAuthenticated: boolean;
  
}>) {
  return (
    <html>
      <body>
        <div>
          <Navbar isAuthenticated={isAuthenticated}/>
          <main>{children}</main>
        </div>
      </body>
    </html>
    );
}